version: "3"

services:
  postgres:
    image: postgres:alpine3.16
    container_name: postgres
    restart: always
    environment:
      - XABARAS=S
      - POSTGRES_DB=ecommerce
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - "./scripts/database.sql:/docker-entrypoint-initdb.d/database.sql"
    ports:
      - "5432:5432"